mode: deployment

presets:
  # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
  kubernetesAttributes:
    enabled: true
  # enables the kubeletstatsreceiver and adds it to the metrics pipelines
  kubeletMetrics:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  exporters:
    otlphttp:
      endpoint: "https://aaaaddhwxvhc2aaaaaaaaacxwm.apm-agt.us-ashburn-1.oci.oraclecloud.com/20200101/opentelemetry"
      headers:
        Authorization: "dataKey UTPWZYWS22NJWQYUCEJKSCXPNJJKKFJK"
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [otlphttp]
      traces:
        receivers: [otlp]
        exporters: [otlphttp]
