apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasource-app
  labels:
    app: datasource-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datasource-app
      version: v1
  template:
    metadata:
      labels:
        app: datasource-app
        version: v1
    spec:
      containers:
      - name: datasource-app
        image: nrt.ocir.io/orasejapan/otel-demo-app-datasource
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_SERVICE_NAME
          value: otel-helidon-datasource
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: http/protobuf
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: http/protobuf
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: apm-secret
              key: traces-endpoint
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: apm-secret
              key: metrics-endpoint
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: apm-secret
              key: private-key-header
---
apiVersion: v1
kind: Service
metadata:
  name: datasource-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: datasource-app