apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
      version: v1
  template:
    metadata:
      labels:
        app: frontend-app
        version: v1
    spec:
      containers:
      - name: frontend-app
        image: nrt.ocir.io/orasejapan/codeatcustomer/frontend-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: frontend-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-app
            port:
              number: 8082