apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: all-v3
spec:
  hosts:
    - backend-app
  http:
  - route:
    - destination:
        host: backend-app
        subset: v3