apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: v1-v2-half
spec:
  hosts:
    - backend-app
  http:
  - route:
    - destination:
        host: backend-app
        subset: v1
      weight: 50
    - destination:
        host: backend-app
        subset: v2
      weight: 50